import {
  // ElAlert,
  ElAside,
  // ElAutocomplete,
  // ElAvatar,
  // ElBacktop,
  // ElBadge,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElButton,
  // ElButtonGroup,
  // ElCalendar,
  ElCard,
  // ElCarousel,
  // ElCarouselItem,
  // ElCascader,
  // ElCascaderPanel,
  ElCheckbox,
  // ElCheckboxButton,
  ElCheckboxGroup,
  ElCol,
  // ElCollapse,
  // ElCollapseItem,
  ElCollapseTransition,
  // ElColorPicker,
  ElContainer,
  ElDatePicker,
  ElDialog,
  ElDivider,
  // ElDrawer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  // ElFooter,
  ElForm,
  ElFormItem,
  ElHeader,
  ElIcon,
  // ElImage,
  ElInput,
  ElInputNumber,
  ElLink,
  ElMain,
  ElMenu,
  ElMenuItem,
  // ElMenuItemGroup,
  ElOption,
  // ElOptionGroup,
  // ElPageHeader,
  ElPagination,
  // ElPopconfirm,
  // ElPopover,
  // ElPopper,
  // ElProgress,
  ElRadio,
  // ElRadioButton,
  ElRadioGroup,
  // ElRate,
  ElRow,
  ElScrollbar,
  ElSelect,
  // ElSlider,
  // ElStep,
  // ElSteps,
  ElSubmenu,
  // ElSwitch,
  ElTabPane,
  ElTable,
  ElTableColumn,
  ElTabs,
  // ElTag,
  ElTimePicker,
  ElTimeSelect,
  // ElTimeline,
  // ElTimelineItem,
  // ElTooltip,
  ElTransfer,
  ElTree,
  // ElUpload,
  // ElInfiniteScroll,
  ElLoading,
  ElMessage,
  // ElMessageBox,
  // ElNotification
  locale,
} from 'element-plus'
import lang from 'element-plus/lib/locale/lang/zh-cn'
import 'dayjs/locale/zh-cn'
import type { App, Component, Plugin } from 'vue'

const components: Component[] = [
  // ElAlert,
  ElAside,
  // ElAutocomplete,
  // ElAvatar,
  // ElBacktop,
  // ElBadge,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElButton,
  // ElButtonGroup,
  // ElCalendar,
  ElCard,
  // ElCarousel,
  // ElCarouselItem,
  // ElCascader,
  // ElCascaderPanel,
  ElCheckbox,
  // ElCheckboxButton,
  ElCheckboxGroup,
  ElCol,
  // ElCollapse,
  // ElCollapseItem,
  ElCollapseTransition,
  // ElColorPicker,
  ElContainer,
  ElDatePicker,
  ElDialog,
  ElDivider,
  // ElDrawer,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  // ElFooter,
  ElForm,
  ElFormItem,
  ElHeader,
  ElIcon,
  // ElImage,
  ElInput,
  ElInputNumber,
  ElLink,
  ElMain,
  ElMenu,
  ElMenuItem,
  // ElMenuItemGroup,
  ElOption,
  // ElOptionGroup,
  // ElPageHeader,
  ElPagination,
  // ElPopconfirm,
  // ElPopover,
  // ElPopper,
  // ElProgress,
  ElRadio,
  // ElRadioButton,
  ElRadioGroup,
  // ElRate,
  ElRow,
  ElScrollbar,
  ElSelect,
  // ElSlider,
  // ElStep,
  // ElSteps,
  ElSubmenu,
  // ElSwitch,
  ElTabPane,
  ElTable,
  ElTableColumn,
  ElTabs,
  // ElTag,
  ElTimePicker,
  ElTimeSelect,
  // ElTimeline,
  // ElTimelineItem,
  // ElTooltip,
  ElTransfer,
  ElTree,
  // ElUpload,
]

const plugins: any[] = [
  // ElInfiniteScroll,
  ElLoading,
  ElMessage,
  // ElMessageBox,
  // ElNotification,
]

export default (app: App): void => {
  // console.log(locale, lang)
  // 在打包项目时，发现生产环境下的bug，locale不是函数，而是个对象 { use, t, i18n } 兼容处理
  if(import.meta.env.MODE === 'production' && Reflect.has(locale, 'use')) {
    locale.use(lang)
  } else {
    locale(lang)
  }

  // 全局配置
  app.config.globalProperties.$ELEMENT = { size: 'small', zIndex: 3000 }

  components.forEach((component: Component): void => {
    app.component(component.name!, component)
  })

  plugins.forEach((plugin: Plugin): void => {
    app.use(plugin)
  })
}